# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f90471fadec95d66f4deb3f1a46c36a8bdec2ada509be8f3215b1b5ac17577da362e2fbcba989f9e0ae72845bf85d7ad6430134b4ad3d89e8b8c62ea9095f62

test:
  secret_key_base: 9c0a3dcf4b282f707936f79d5e39731a2eda3ff92a5ba2d4dd39f860ffed40b48e902481f96760436e86775f8b9093bbdbf2e80a8e2ce074ba17390aac8f8569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
